version: '3'
services:
  database:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - 5432:5432
  jaeger:
    image: jaegertracing/all-in-one:1.33.0
    volumes:
      - ./jaeger-ui.json:/etc/jaeger/jaeger-ui.json
    command: --query.ui-config /etc/jaeger/jaeger-ui.json
    environment:
      METRICS_STORAGE_TYPE: prometheus
      PROMETHEUS_SERVER_URL: http://prometheus:9090
    ports:
      - 14250:14250
      - 14268:14268
      - 6831:6831/udp
      - 16686:16686
      - 16685:16685
  prometheus:
    image: prom/prometheus:v2.35.0
    volumes:
      - "./jaeger-prometheus.yaml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  otel_collector:
    image: otel/opentelemetry-collector-contrib:0.50.0
    volumes:
      - "./jaeger-otel-collector.yaml:/etc/otelcol/otel-collector-config.yml"
    command: --config /etc/otelcol/otel-collector-config.yml
    depends_on:
      - jaeger
    ports:
      - 14278:14278